site_name: Awesome Russian IT
site_url: https://awesomeit.ru
site_description: 'Список полезных русскоязычных ресурсов, связанных с информационными технологиями (разработка, администрирование, митапы и конференции, интервью, новости ИТ и пр.)'
site_author: Chebotov Nikolay (Unchase)
repo_name: unchase/awesome-russian-it
repo_url: https://github.com/unchase/awesome-russian-it
edit_uri: ""
google_analytics:
  - UA-124134438-2
  - auto
nav:
    - События и блоги: index.md
    - Подкасты: Podcasts.md
    - YouTube-каналы: YouTube.md
    - Contributing: CONTRIBUTING.md
theme:
  name: 'material'
  favicon: img/favicon.ico
  palette:
    primary: light blue
  language: ru
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - toc.integrate
plugins:
  - search:
      lang:
        - en
        - ru
extra:
  generator: false
  social:
    - icon: fontawesome/brands/chrome
      link: https://unchase.ru/
      name: Основной сайт
    - icon: fontawesome/brands/paypal
      link: https://www.buymeacoffee.com/nikolaychebotov
      name: Основной сайт
    - icon: fontawesome/brands/github
      link: https://github.com/unchase
    - icon: fontawesome/brands/medium
      link: https://medium.com/@unchase
    - icon: fontawesome/brands/dev
      link: https://dev.to/unchase
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/unchase12