name: Update_Podcasts_Data

on:
  schedule:
    - cron: '0 5-20/4 * * *'

##on:
##  push:
##    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: ls
      run: ls
    - name: Set chmod to Unchase.HtmlTagsUpdater
      run: chmod 777 ./utils/Unchase.HtmlTagsUpdater
    - name: Run Unchase.HtmlTagsUpdater (with Telegram Bot)
      env:
        TG_KEY: ${{ secrets.TgKey }}
        TG_CHANNEL_ID: ${{ secrets.TgChannelId }}
      run: ./utils/Unchase.HtmlTagsUpdater -f "Podcasts.md" -t "iTunesPodcast" -a "$TG_KEY" -c "$TG_CHANNEL_ID" -i "150"
      
    - name: Show Podcasts.md
      run: cat Podcasts.md
      
    - name: Git status
      run: /usr/bin/git status
      
    - name: Git set author (email)
      run: /usr/bin/git config --global user.name "GitHub Action Unchase"
      
    - name: Git set author (email)
      run: /usr/bin/git config --global user.email "spiritkola@hotmail.com"

    - name: Git add
      run: /usr/bin/git add Podcasts.md
      
    - name: Git commit
      run: /usr/bin/git commit -m "Update podcasts data"
      
    - name: Git push
      run: /usr/bin/git push origin master
